In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import joblib

# Load dataset
df = pd.read_csv('/kaggle/input/heart-attack-dataset-tarik-a-rashid/Medicaldataset.csv')

df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1319 non-null   int64
 1   Gender                    1319 non-null   int64
 2   Heart rate                1319 non-null   int64
 3   Systolic blood pressure   1319 non-null   int64
 4   Diastolic blood pressure  1319 non-null   int64
 5   Blood sugar               1319 non-null   float64
 6   CK-MB                     1319 non-null   float64
 7   Troponin                  1319 non-null   float64
 8   Result                    1319 non-null   object
dtypes: float64(3), int64(5), object(1)
memory usage: 92.9+ KB

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Result
0,64,1,66,160,83,160.0,1.80,0.012,negative
1,21,1,94,98,46,296.0,6.75,1.060,positive
2,55,1,64,160,77,270.0,1.99,0.003,negative
3,64,1,70,120,55,270.0,13.87,0.122,positive
4,55,1,64,112,65,300.0,1.08,0.003,negative
...,...,...,...,...,...,...,...,...,...
1314,44,1,94,122,67,204.0,1.63,0.006,negative
1315,66,1,84,125,55,149.0,1.33,0.172,positive
1316,45,1,85,168,104,96.0,1.24,4.250,positive
1317,54,1,58,117,68,443.0,5.80,0.359,positive
1318,51,1,94,157,79,134.0,50.89,1.770,positive

In [23]:
df.shape

(1319, 9)

In [24]:
df.isnull().sum()

Age                         0
Gender                      0
Heart rate                  0
Systolic blood pressure     0
Diastolic blood pressure    0
Blood sugar                 0
CK-MB                       0
Troponin                    0
Result                      0
dtype: int64

In [25]:
# Encode Result
df['Result'] = df['Result'].map({'positive': 1, 'negative': 0})

# Features and target
X = df.drop('Result', axis=1)
y = df['Result']

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Save model
joblib.dump(model, 'heart_model.pkl')

# Optional: Evaluate
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       101
           1       0.99      0.99      0.99       163

    accuracy                           0.98       264
   macro avg       0.98      0.98      0.98       264
weighted avg       0.98      0.98      0.98       264

In [27]:
pip show joblib

Name: joblib
Version: 1.5.0
Summary: Lightweight pipelining with Python functions
Home-page: https://joblib.readthedocs.io
Author:
Author-email: Gael Varoquaux <gael.varoquaux@normalesup.org>
License: BSD 3-Clause
Location: /usr/local/lib/python3.11/dist-packages
Requires:
Required-by: cesium, cuml-cu12, hdbscan, imbalanced-learn, librosa, mlxtend, music21, nilearn, nltk, osqp, phik, pyLDAvis, pynndescent, rgf-python, scikit-learn, scikit-optimize, scikit-plot, scikit-surprise, TPOT
Note: you may need to restart the kernel to use updated packages.